import { Box, Button, GridItem, Heading, Text } from "@chakra-ui/react";

import Head from "next/head";
import { Layout } from "../../components/Layout";
import React, { useState } from "react";

import { NextPage } from "next";
import Link from "next/link";

import { TeamAttributes } from "../../types/cms";

import { TeamBadge } from "../../components/teamBadge";

type HomepageProps = {
  teams: TeamAttributes[];
};

const Home: NextPage<HomepageProps> = () => {
  const [selectedTeam, setSelectedTeam] = useState<string | undefined>();

  const handleTeamClick = (id: string) => {
    setSelectedTeam(id);
  };

  return (
    <div>
      <Head>
        <title>Mijn onboarding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box as="main" display="flex" justifyContent="center">
        <Layout>
          <GridItem
            colSpan={12}
            margin="0 2rem"
            display="flex"
            justifyContent="center"
            textAlign="center"
            flexDirection="column"
          >
            <Heading
              as="h1"
              size="4xl"
              marginBottom="2.5rem"
              bgGradient="linear(to-l, #7928CA, #FF0080)"
              fontWeight="extrabold"
              bgClip="text"
            >
              The teams
            </Heading>
          </GridItem>
          <TeamBadge
            image="/snail.jpg"
            name="Turbo snails"
            selected={selectedTeam === "sales"}
            onClick={handleTeamClick}
            identifier="sales"
          />
          <TeamBadge
            image="/snail.jpg"
            name="Pro ducks"
            selected={selectedTeam === "products"}
            onClick={handleTeamClick}
            identifier="products"
          />
          <TeamBadge
            selected={selectedTeam === "busines"}
            image="/snail.jpg"
            name="busy bees"
            onClick={handleTeamClick}
            identifier="busines"
          />
          <GridItem
            colSpan={12}
            rounded="lg"
            background="#31203F"
            color="#E1E1E1"
            p="2rem"
            my="4rem"
          >
            <Text fontSize="lg" fontWeight="bold">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Sapien
              et ligula ullamcorper malesuada proin libero nunc consequat. Eget
              magna fermentum iaculis eu non diam phasellus vestibulum. Libero
              id faucibus nisl tincidunt eget. Est ullamcorper eget nulla
              facilisi etiam dignissim diam quis enim. At in tellus integer
              feugiat scelerisque varius morbi. Vitae purus faucibus ornare
              suspendisse sed nisi lacus sed. Purus gravida quis blandit turpis
              cursus. Hac habitasse platea dictumst vestibulum rhoncus. Sed
              risus ultricies tristique nulla aliquet enim tortor.
            </Text>
          </GridItem>
          <GridItem colStart={5} colEnd={9}>
            <Link href={`/onboarding/${selectedTeam}?chapter=1&step=1`}>
              <Button
                w="100%"
                size="lg"
                fontWeight="bold"
                fontSize="4xl"
                py="2.5rem"
                color="#F2F2F2"
                bgColor="#7928CA"
                disabled={!selectedTeam}
                _hover={{ bg: "#7928CA" }}
              >
                continue
              </Button>
            </Link>
          </GridItem>
        </Layout>
      </Box>

      <footer></footer>
    </div>
  );
};

export default Home;
