import { Box, Button, GridItem, Heading, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "../components/Layout";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import React from "react";

import dynamic from "next/dynamic";

const Spline = dynamic(() => import("@splinetool/react-spline"), {
  ssr: false,
  loading: () => <h1>loading...</h1>,
});

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box as="main" display="flex" justifyContent="center">
        <Layout>
          <GridItem
            colSpan={12}
            margin="0 2rem"
            display="flex"
            justifyContent="center"
            textAlign="center"
            flexDirection="column"
          >
            <Heading
              as="h1"
              fontSize="8rem"
              marginBottom="2.5rem"
              bgGradient="linear(to-l, #7928CA, #FF0080)"
              fontWeight="extrabold"
              bgClip="text"
            >
              My onboarding
            </Heading>
          </GridItem>
          <GridItem colSpan={12} height="43rem">
            <Spline scene="https://prod.spline.design/8-XX3fWBmbcS9if7/scene.splinecode" />
          </GridItem>
          <GridItem colStart={5} colEnd={9}>
            <Link href="/onboarding">
              <Button
                w="100%"
                size="lg"
                fontWeight="bold"
                fontSize="4xl"
                py="2.5rem"
                color="#F2F2F2"
                bgColor="#7928CA"
                _hover={{ bg: "#7928CA" }}
              >
                Start onboarding
              </Button>
            </Link>
          </GridItem>
        </Layout>
      </Box>

      <footer className={styles.footer}>
        Created with love by: Rene van Dijk
      </footer>
    </div>
  );
};

export default Home;
